[package]
name = "calibrator"
version = "0.1.0"
edition = "2024"
authors = ["0x484558 <0x484558@pm.me>"]
description = "HDR balance calibrator daemon"

[workspace]
members = [".", "xtask"]
default-members = ["."]
resolver = "3"

[lints.rust]
unsafe_op_in_unsafe_fn = "deny"

[target.'cfg(windows)'.dependencies]
futures = "0.3.31"
serde = { version = "1.0.228", features = ["derive"] }
windows = { version = "0.62.2", features = [
    "Win32_Devices_Display",
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_Security",
    "Win32_System_Com",
    "Win32_System_EventLog",
    "Win32_System_LibraryLoader",
    "Win32_System_Power",
    "Win32_System_RemoteDesktop",
    "Win32_System_StationsAndDesktops",
    "Win32_System_SystemServices",
    "Win32_System_Threading",
    "Win32_UI_Shell",
    "Win32_UI_WindowsAndMessaging",
] }
wmi = { version = "0.18.4", default-features = false }

[profile.release]
codegen-units = 1
lto = "thin"
panic = "abort"
strip = "symbols"
